---
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    -  "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yaml

- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

- name: Check if cluster_type is defined when running EL6
  fail:
    msg: 'cluster_type must be defined on EL6 for tagging variant'
  when: ansible_distribution_major_version == "6" and not cluster_type and HALVMtype == "tagging"

- name: Check if proper HALVMtype is selected for EL8 platform
  fail:
    msg: 'On EL8 you have use HALVMtype:"systemid" at the moment.'
  when: ansible_distribution_major_version == "8" and HALVMtype != "systemid"
