---
old_versions:
    - docker-ce
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
