---
- name: "Make sure docker service is running"
  systemd:
    state: started
    enabled: yes
    name: docker
- name: "Ensure group docker exists"
  group:
    name: docker
    state: present
- name: "Manage Docker as a non-root user"
  user:
    name: vagrant
    groups: docker
    append: yes
