---
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
      - default.yml

- name: "Uninstall old versions"
  package:
    name: '{{ old_versions }}'
    use: '{{ ansible_pkg_mgr }}'
    state: absent

- name: "Uninstall old versions"
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    # - docker-ce
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: "Delete all images, containers, and volumes"
  file:
    path: /var/lib/docker
    state: absent

# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes

- name: "Install packages x to allow apt to use a repository over HTTPS"
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker APT repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present

- name: "Install the latest version of Docker Engine - Community"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: "Make sure docker service is running"
  systemd:
    state: started
    enabled: yes
    name: docker

- name: "Ensure group docker exists"
  group:
    name: docker
    state: present

- name: "Manage Docker as a non-root user"
  user:
    name: vagrant
    groups: docker
    append: yes
